### ISSUE TITLE
Sharing S3 Buckets

### ISSUE THREAD

**Issue by skalermo** [zdoryk/alcon-de-aws-workshop-students#3]
@zdoryk Hey, just pinging to let you know that I shared the S3 buckets in [README.md](https://github.com/zdoryk/alcon-de-aws-workshop-students/blob/dev/roman/README.md). Let me know if it's ok.

**Comment by zdoryk** [comment]
@skalermo will check tomorrow, I am in train rn

**Comment by zdoryk** [comment]
Good job with sharing the bucket like this, can you please paste the link to the source where you've found how to do that to the wiki for other students to refer to. 

Regarding you data, it's mostly looking good, the only thing is that you've made a misstake in the check where "is_dead" column was created:
<img width="384" alt="obraz" src="https://github.com/zdoryk/alcon-de-aws-workshop-students/assets/63752476/d8406c54-a723-4342-8000-d2ef75af7109">
As you can see from the screenshot, you have the oposite to the task. In your data if perso has "9999-99-99" in the "DATE_DIED" column you mark it as person is dead eg. is_dead = true. But it should be opposite, cause if the person died before this person will have the actual date of death in the "DATE_DIED" column. So you just need to replace the check in the task #2

**Comment by zdoryk** [comment]
Beside this data is looking good, the code is also looks fine, good job!

**Comment by skalermo** [comment]
> In your data if perso has "9999-99-99" in the "DATE_DIED" column you mark it as person is dead eg. is_dead = true. But it should be opposite

Good catch! I pushed the fix and reran lambdas/glue - the latest data should be alright.

**Comment by skalermo** [comment]
> Good job with sharing the bucket like this, can you please paste the link to the source where you've found how to do that to the wiki for other students to refer to.

I followed instructions from https://github.com/rufuspollock/s3-bucket-listing. I'll post my setup in a wiki page.

EDIT: [link](https://github.com/zdoryk/alcon-de-aws-workshop-students/wiki/Sharing-S3-Bucket) to the wiki page.
