### ISSUE TITLE
I am having this error since yesterday.

### ISSUE THREAD

**Issue by supernovaedge** [zdoryk/alcon-de-aws-workshop-students#4]
![image](https://github.com/zdoryk/alcon-de-aws-workshop-students/assets/104095410/c115397f-849f-44a6-9e5a-c0fff5d17a09)

**Comment by zdoryk** [comment]
Check your rights in IAM, and try to reload the page or enter through another browser or incognito mode. This is 99.99% not the problem of terraform cause from what I see you even can't list the Lambda Functions on your account

**Comment by skalermo** [comment]
It appears to be a [common](https://repost.aws/questions/QUDhTKkMfnRp6JGus4Ko_3mg/lambda-functions-are-gone-unknown-error) issue.

**Comment by skalermo** [comment]
@zdoryk Do you think this issue could occur because of credentials leak in the commit? Specifically ACCESS_KEY_ID and SECRET_ACCESS_KEY.

**Comment by supernovaedge** [comment]
Opening AWS in incognito worked, thanks. everything else didn't work. I removed access key from aws yesterday, so that probably didn't cause the error.
